on:
  push:
  pull_request_target:

env:
  A: 1
  "B": 2
  $C: 3

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env }}
      - run: echo ${{ github.event.pull_request.title }}
